### ISSUE TITLE
cora validation/test IDs inconsistent with planetoid

### ISSUE THREAD

**Issue by jackd** [wokas36/DFNets#3]
I may be mistaken, but the validation / test ids set [here](https://github.com/wokas36/DFNets/blob/master/dfnet/utils.py#L133) seem inconsistent with those used in [planetoid](https://github.com/kimiyoung/planetoid). My understanding of simplified splits below.

DFNets (this repo):
```python
idx_val = range(140, 1000)
idx_test = range(1000, 2000)
```

Planetoid:
```python
idx_val = range(140, 640)
idx_test = range(1708, 2708)
```

Do you have any comment on this?

**Comment by wokas36** [comment]
Hi Jackd,
We used the same data splits as planetoid in our experimental setup. I couldn't remember exactly, but I think we added this line to assess the robustness of our model by varying the validation and testing splits randomly (it should be evaluating our models with random splits and imbalance training samples). Hope that our reply can help you.
